CREATE DATABASE IF NOT EXISTS prestashop;
CREATE USER IF NOT EXISTS 'lvintila'@'localhost' IDENTIFIED BY '007009';
GRANT ALL PRIVILEGES ON *.* TO 'lvintila'@'localhost'IDENTIFIED BY '007009';
FLUSH PRIVILEGES;