CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'lvintila'@'%' IDENTIFIED BY '007009';
GRANT ALL PRIVILEGES ON wordpress.* TO 'lvintila'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
